-- emoeat database schema
USE emoeat;

CREATE TABLE IF NOT EXISTS USERS (
    ID_USER     INT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(100)  NOT NULL,
    EMAIL       VARCHAR(150)  NOT NULL UNIQUE,
    PASSWORD    VARCHAR(255)  NOT NULL,
    ROLE        ENUM('CLIENT','ADMIN') NOT NULL DEFAULT 'CLIENT',
    CREATED_AT  DATETIME      NOT NULL DEFAULT NOW()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CLIENT (
    ID_USER INT PRIMARY KEY,
    CONSTRAINT fk_client_user FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ADMIN (
    ID_USER INT PRIMARY KEY,
    CONSTRAINT fk_admin_user FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EMOTIONS (
    ID_EMOTION   INT AUTO_INCREMENT PRIMARY KEY,
    EMOTION_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION  TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FOODS (
    ID_FOOD     INT AUTO_INCREMENT PRIMARY KEY,
    FOOD_NAME   VARCHAR(150)   NOT NULL,
    CATEGORY    VARCHAR(100),
    CALORIES    INT            NOT NULL DEFAULT 0,
    PROTEIN     DECIMAL(6,2)   NOT NULL DEFAULT 0,
    CARBS       DECIMAL(6,2)   NOT NULL DEFAULT 0,
    FAT         DECIMAL(6,2)   NOT NULL DEFAULT 0,
    DESCRIPTION TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EMOTION_FOOD (
    ID_RULE    INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMOTION INT NOT NULL,
    ID_FOOD    INT NOT NULL,
    INTENSITY  INT NOT NULL DEFAULT 1,
    CONSTRAINT fk_ef_emotion FOREIGN KEY (ID_EMOTION) REFERENCES EMOTIONS(ID_EMOTION) ON DELETE CASCADE,
    CONSTRAINT fk_ef_food    FOREIGN KEY (ID_FOOD)    REFERENCES FOODS(ID_FOOD)        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_EMOTIONS (
    ID           INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER      INT NOT NULL,
    ID_EMOTION   INT NOT NULL,
    EMOTION_DATE DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_ue_user    FOREIGN KEY (ID_USER)    REFERENCES USERS(ID_USER)      ON DELETE CASCADE,
    CONSTRAINT fk_ue_emotion FOREIGN KEY (ID_EMOTION) REFERENCES EMOTIONS(ID_EMOTION) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_PROFILE (
    ID_USER    INT PRIMARY KEY,
    WEIGHT     DECIMAL(5,2),
    HEIGHT     DECIMAL(5,2),
    ALLERGIES  TEXT,
    GOAL       TEXT,
    CONSTRAINT fk_up_user FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RECOMMENDATIONS (
    ID_REC              INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMOTION          INT NOT NULL,
    ID_FOOD             INT NOT NULL,
    BENEFIT             TEXT,
    ID_USER             INT NOT NULL,
    RECOMMENDATION_DATE DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_rec_emotion FOREIGN KEY (ID_EMOTION) REFERENCES EMOTIONS(ID_EMOTION) ON DELETE CASCADE,
    CONSTRAINT fk_rec_food    FOREIGN KEY (ID_FOOD)    REFERENCES FOODS(ID_FOOD)        ON DELETE CASCADE,
    CONSTRAINT fk_rec_user    FOREIGN KEY (ID_USER)    REFERENCES USERS(ID_USER)        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ACTIVITY_LOG (
    ID_LOG   INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER  INT NOT NULL,
    ACTION   VARCHAR(255) NOT NULL,
    LOG_DATE DATETIME NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_al_user FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKENS (
    ID_TOKEN   INT AUTO_INCREMENT PRIMARY KEY,
    ID_USER    INT          NOT NULL,
    TOKEN      VARCHAR(255) NOT NULL UNIQUE,
    EXPIRES_AT DATETIME     NOT NULL,
    USED       TINYINT(1)   NOT NULL DEFAULT 0,
    CONSTRAINT fk_prt_user FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
